// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Clublist': typeof import('../components/Clublist.vue')['default'],
    'ListCard': typeof import('../components/ListCard.vue')['default'],
    'RegattaHighlight': typeof import('../components/RegattaHighlight.vue')['default'],
    'RegattaList': typeof import('../components/RegattaList.vue')['default'],
    'RegattaSearch': typeof import('../components/RegattaSearch.vue')['default'],
    'ResultDetails': typeof import('../components/ResultDetails.vue')['default'],
    'ResultsTable': typeof import('../components/ResultsTable.vue')['default'],
    'SimpleCard': typeof import('../components/SimpleCard.vue')['default'],
    'Table': typeof import('../components/Table.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
